### ISSUE TITLE
Return chrono::NaiveDate

### ISSUE THREAD

**Issue by manuelVo** [dten/computus#2]
For tighter integration into the existing DateTime infrastructure of rust it would be great if there was an option to return a chrono::NaiveDate instead of the create's custom Date type.

**Comment by dten** [comment]
Sounds reasonable. I would probably do it as an optional feature.

**Comment by manuelVo** [comment]
Agreed. Putting it behind a feature flag allows people to avoid pulling in dependencies they don't need, which is always nice :)

**Comment by dten** [comment]
Resolved with v1.1.0

https://github.com/dten/computus/releases/tag/v1.1.0
